"""initial 16 tables

Revision ID: c2ca883fc104
Revises: 
Create Date: 2026-05-10 12:26:25.846474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2ca883fc104'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('period_from', sa.Date(), nullable=True),
    sa.Column('period_to', sa.Date(), nullable=True),
    sa.Column('recommendation_accuracy', sa.Numeric(), nullable=True),
    sa.Column('price_error_mean', sa.Numeric(), nullable=True),
    sa.Column('portfolio_roi', sa.Numeric(), nullable=True),
    sa.Column('vnindex_roi', sa.Numeric(), nullable=True),
    sa.Column('alpha', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cache_metadata',
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('ttl_hours', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('source')
    )
    op.create_table('macro_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('indicator', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_macro_indicator_period', 'macro_data', ['indicator', 'period'], unique=True)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('content_snippet', sa.Text(), nullable=True),
    sa.Column('related_tickers_json', sa.Text(), nullable=True),
    sa.Column('sentiment_label', sa.String(), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(), nullable=True),
    sa.Column('sentiment_reason', sa.Text(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('idx_news_published', 'news_articles', ['published_at'], unique=False)
    op.create_index('idx_news_source', 'news_articles', ['source'], unique=False)
    op.create_table('screening_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('settings_version', sa.Integer(), nullable=False),
    sa.Column('total_capital', sa.Numeric(), nullable=False),
    sa.Column('thresholds_json', sa.Text(), nullable=True),
    sa.Column('data_from_cache', sa.Boolean(), nullable=False),
    sa.Column('total_input', sa.Integer(), nullable=True),
    sa.Column('after_round_1', sa.Integer(), nullable=True),
    sa.Column('after_round_2', sa.Integer(), nullable=True),
    sa.Column('after_round_3', sa.Integer(), nullable=True),
    sa.Column('after_round_4', sa.Integer(), nullable=True),
    sa.Column('scored_count', sa.Integer(), nullable=True),
    sa.Column('buy_count', sa.Integer(), nullable=True),
    sa.Column('hold_count', sa.Integer(), nullable=True),
    sa.Column('sell_count', sa.Integer(), nullable=True),
    sa.Column('warnings_json', sa.Text(), nullable=True),
    sa.Column('telegram_sent', sa.Boolean(), nullable=False),
    sa.Column('telegram_error', sa.Text(), nullable=True),
    sa.Column('run_error', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(), nullable=True),
    sa.Column('current_step', sa.String(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('idx_runs_run_at', 'screening_runs', ['run_at'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('buy_threshold', sa.Integer(), nullable=False),
    sa.Column('hold_min_threshold', sa.Integer(), nullable=False),
    sa.Column('default_capital', sa.Numeric(), nullable=False),
    sa.Column('source_cafef', sa.Boolean(), nullable=False),
    sa.Column('source_vnexpress', sa.Boolean(), nullable=False),
    sa.Column('source_vietstock', sa.Boolean(), nullable=False),
    sa.Column('source_batdongsan', sa.Boolean(), nullable=False),
    sa.Column('source_thanhnien', sa.Boolean(), nullable=False),
    sa.Column('telegram_enabled', sa.Boolean(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(), nullable=False),
    sa.Column('telegram_token', sa.String(), nullable=False),
    sa.Column('telegram_top_n', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('classic_mode', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('newly_listed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_index('idx_stocks_status', 'stocks', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('based_on_run_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('backtest_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('predicted_recommendation', sa.String(), nullable=True),
    sa.Column('actual_return_3m', sa.Numeric(), nullable=True),
    sa.Column('predicted_price', sa.Numeric(), nullable=True),
    sa.Column('actual_price', sa.Numeric(), nullable=True),
    sa.Column('price_error_pct', sa.Numeric(), nullable=True),
    sa.Column('recommendation_correct', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bt_results_backtest', 'backtest_results', ['backtest_id'], unique=False)
    op.create_table('excluded_stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('excluded_round', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['screening_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_excluded_run', 'excluded_stocks', ['run_id'], unique=False)
    op.create_table('financial_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(), nullable=True),
    sa.Column('net_income', sa.Numeric(), nullable=True),
    sa.Column('total_assets', sa.Numeric(), nullable=True),
    sa.Column('total_equity', sa.Numeric(), nullable=True),
    sa.Column('total_debt', sa.Numeric(), nullable=True),
    sa.Column('current_assets', sa.Numeric(), nullable=True),
    sa.Column('current_liabilities', sa.Numeric(), nullable=True),
    sa.Column('inventory', sa.Numeric(), nullable=True),
    sa.Column('cogs', sa.Numeric(), nullable=True),
    sa.Column('operating_cash_flow', sa.Numeric(), nullable=True),
    sa.Column('eps', sa.Numeric(), nullable=True),
    sa.Column('bvps', sa.Numeric(), nullable=True),
    sa.Column('advances', sa.Numeric(), nullable=True),
    sa.Column('shares_outstanding', sa.Integer(), nullable=True),
    sa.Column('audit_opinion', sa.String(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fin_ticker_period', 'financial_reports', ['ticker', 'period'], unique=True)
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('buy_price', sa.Numeric(), nullable=False),
    sa.Column('buy_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('buy_price > 0', name='ck_portfolio_price_positive'),
    sa.CheckConstraint('quantity > 0', name='ck_portfolio_qty_positive'),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_portfolio_ticker', 'portfolio', ['ticker'], unique=False)
    op.create_table('screening_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('ai_score', sa.Numeric(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('confidence_raw', sa.Numeric(), nullable=True),
    sa.Column('confidence_penalty', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('target_price_3m', sa.Numeric(), nullable=True),
    sa.Column('current_price', sa.Numeric(), nullable=True),
    sa.Column('upside_pct', sa.Numeric(), nullable=True),
    sa.Column('entry_signal', sa.String(), nullable=True),
    sa.Column('entry_reason_code', sa.String(), nullable=True),
    sa.Column('support_zone', sa.Numeric(), nullable=True),
    sa.Column('resistance_zone', sa.Numeric(), nullable=True),
    sa.Column('stop_loss_price', sa.Numeric(), nullable=True),
    sa.Column('allocation_amount', sa.Numeric(), nullable=True),
    sa.Column('allocation_weight', sa.Numeric(), nullable=True),
    sa.Column('warning_badges_json', sa.Text(), nullable=True),
    sa.Column('reasons_json', sa.Text(), nullable=True),
    sa.Column('feature_values_json', sa.Text(), nullable=True),
    sa.Column('feature_availability', sa.Integer(), nullable=True),
    sa.Column('radar_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['screening_runs.run_id'], ),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_results_run', 'screening_results', ['run_id'], unique=False)
    op.create_index('idx_results_run_ticker', 'screening_results', ['run_id', 'ticker'], unique=True)
    op.create_table('share_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['screening_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_share_token', 'share_links', ['token'], unique=True)
    op.create_table('stock_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(), nullable=True),
    sa.Column('high', sa.Numeric(), nullable=True),
    sa.Column('low', sa.Numeric(), nullable=True),
    sa.Column('close', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('ceiling', sa.Numeric(), nullable=True),
    sa.Column('floor', sa.Numeric(), nullable=True),
    sa.Column('reference', sa.Numeric(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prices_date', 'stock_prices', ['date'], unique=False)
    op.create_index('idx_prices_ticker_date', 'stock_prices', ['ticker', 'date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_prices_ticker_date', table_name='stock_prices')
    op.drop_index('idx_prices_date', table_name='stock_prices')
    op.drop_table('stock_prices')
    op.drop_index('idx_share_token', table_name='share_links')
    op.drop_table('share_links')
    op.drop_index('idx_results_run_ticker', table_name='screening_results')
    op.drop_index('idx_results_run', table_name='screening_results')
    op.drop_table('screening_results')
    op.drop_index('idx_portfolio_ticker', table_name='portfolio')
    op.drop_table('portfolio')
    op.drop_index('idx_fin_ticker_period', table_name='financial_reports')
    op.drop_table('financial_reports')
    op.drop_index('idx_excluded_run', table_name='excluded_stocks')
    op.drop_table('excluded_stocks')
    op.drop_index('idx_bt_results_backtest', table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_table('user_profile')
    op.drop_table('transactions')
    op.drop_index('idx_stocks_status', table_name='stocks')
    op.drop_table('stocks')
    op.drop_table('settings')
    op.drop_index('idx_runs_run_at', table_name='screening_runs')
    op.drop_table('screening_runs')
    op.drop_index('idx_news_source', table_name='news_articles')
    op.drop_index('idx_news_published', table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index('idx_macro_indicator_period', table_name='macro_data')
    op.drop_table('macro_data')
    op.drop_table('cache_metadata')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
